### PR TITLE
Snapchat_agent update

### PR DESCRIPTION
**Pull request by LinoSuarez**

### CODE REVIEW

**Comment by hako** [comment]
Tested this, I can confirm it works. 👍

**Comment by hisham-albeik** [comment]
I second that! confirmed as well.

**Comment by Dgameman1** [comment]
Doesn't work for me

**Comment by LinoSuarez** [comment]
@Dgameman1 What error do you get?

**Comment by Dgameman1** [comment]
@LinoSuarez I still get the blocked due to suspicious activity

**Comment by j0rd** [comment]
Worked for me. Before this change, I couldn't login. Now I can login and post.

**Comment by jonjesbuzz** [comment]
This change works for me as well.

**Comment by LinoSuarez** [comment]
@JorgenPhi Merge this, it makes the API work.

**Comment by andre3wap** [comment]
Can anyone confirm if this still works?

**Comment by hunt4car** [comment]
@andre3wap dont think so, I believe snapchat closed all api access for security reasons... I would like to learn otherwise if anyone else sees this...

**Comment by andre3wap** [comment]
@hunt4car  - There are a few apps for android that's still functioning. I'll continue to research, if I find anything I will share with you. 
- Andre

**Pull request merged**
